module.exports = {
  api: null,
  service: null,
  port: null,
  host: null,
  shouldNotPrefetch: [],
  shouldNotPreload: [],
  entry: target => `./src/entry-${target}`,
  defaultTitle: 'My app',
  favicon: './public/favicon.ico',
  criticalCSS: true,
  skipRequests: ctx => ctx.url === '/graphql',
  nodeExternalsWhitelist: [new RegExp(/\.css$/), new RegExp(/\?vue&type=style/)],
  clustered: false,
  maxCluster: null,
  rootPath: null,
  directives: {},
  copyUrlOnStart: true,
  fullControlRender: false,
  onRender: null,
  onBeforeSend: null,
  onError: null,
  distPath: null,
  error500Html: null,
  templatePath: null,
  serviceWorkerPath: null,
  extendMiddlewares: [],
  extendRouter: [],
  customSsrPath: null,
  prodOnly: false,
  modernMode: true,
  componentCache: {
    active: true,
    options: {
      maxAge: 1000 * 60 * 60,
    },
  },
  pageCache: {
    active: true,
    options: {
      maxAge: 1000 * 60 * 60,
    },
    cacheUrls: [],
  },
  middlewares: {
    static: {
      active: true,
      options: {
        maxAge: 1000 * 60 * 60 * 24 * 30,
      },
    },
    cors: true,
    compress: true,
    logger: true,
  },
}
